version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config/mosquitto.conf:/mqtt/config/mosquitto.conf
      - ./mqtt/data:/mqtt/data
    networks:
      - telemetry_net

  engine_simulator:
    build: ./simul
    container_name: engine_simulator
    depends_on:
      - mosquitto
    volumes:
      - ./simul:/app
      - ./shared:/app/shared
    networks:
      - telemetry_net
  
  logger:
    build: ./testing
    container_name: logger
    depends_on:
      - mosquitto
    volumes:
      - ./testing/logs:/app/logs
    networks:
      - telemetry_net

networks:
  telemetry_net:
    driver: bridge