services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - telemetry_net

  engine_simulator:
    build: ./simul
    container_name: engine_simulator
    depends_on:
      - mosquitto
    volumes:
      - ./simul:/app
    networks:
      - telemetry_net
  
  logger:
    build: ./testing
    container_name: logger
    depends_on:
      - mosquitto
    volumes:
      - ./testing/logs:/app/logs
    networks:
      - telemetry_net

networks:
  telemetry_net:
    driver: bridge